### ISSUE TITLE
Please consider add CrossVIS (ICCV 2021) for video instance segmentation

### ISSUE THREAD

**Issue by Yuxin-CV** [tfzhou/VS-Survey#1]
Hello, thanks for the awesome survey & repo!

We believe a related video instance segmentation work CrossVIS (ICCV 2021, paper: https://arxiv.org/abs/2104.05970, code: https://github.com/hustvl/CrossVIS) is missing, please consider add it, thanks!

**Comment by tfzhou** [comment]
@Yuxin-CV Thanks. The paper has been included in the repo, and our survey paper will be updated later.
