### ISSUE TITLE
Please consider adding  RPCM (AAAI 2022) for semi-supervised video object segmentation, thanks!

### ISSUE THREAD

**Issue by JerryX1110** [tfzhou/VS-Survey#2]
Hi, thanks for the awesome survey & repo!

We believe a related semi-supervised video object segmentation work RPCM (AAAI2022, paper: https://arxiv.org/abs/2112.02853, code: https://github.com/JerryX1110/RPCMVOS) is missing, please consider add it, thanks!

**Comment by tfzhou** [comment]
@JerryX1110 Thanks. Repo updated!
