### ISSUE TITLE
Great work! Could you please add papers from our group.

### ISSUE THREAD

**Issue by lxtGH** [tfzhou/VS-Survey#3]
Hi! Dr.Tianfei. @tfzhou .

Could you consider adding three works from our groups on video detection/segmentation. Thanks!!

Video Object Detection by extending DETR. 
TransVOD: End-to-end Video Object Detection with Spatial-Temporal Transformers PAMI-2022, paper: https://arxiv.org/abs/2201.05047 code: https://github.com/SJTU-LuHe/TransVOD

Video Panopitc Segmentation using Query based approaches-CVPR-2022, paper: https://arxiv.org/abs/2204.04656 code: https://github.com/lxtGH/Video-K-Net

Video Instance Segmentation using Dynamic Network, PAMI-2022, paper:  https://arxiv.org/abs/2107.13155 code: https://github.com/lxtGH/TemporalPyramidRouting

Thanks!!!

**Comment by tfzhou** [comment]
@lxtGH Added! Thanks!
